[package]
name = "common"
version = "0.0.0"
edition = "2024"

[dependencies]
serde_json = "1.0.141"
serde = { version = "1.0.219", features = [ "derive" ] }

[lints.clippy]
needless_return = "allow"

[lints.rust]
non_upper_case_globals = "allow"