[package]
name = "autoclicker"
version.workspace = true
edition.workspace = true

[dependencies]
gtk4 = "0.9.7"

tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
nix.workspace = true
serde_json.workspace = true
serde.workspace = true

version.workspace = true
common.workspace = true

[lints.clippy]
needless_return = "allow"